### ISSUE TITLE
SCS Standard Images reference YAML not clearly communicated

### ISSUE THREAD

**Issue by markus-hentsch** [SovereignCloudStack/standards#534]
Putting myself into the perspective of a CSP that aims for SCS conformance I noticed the following shortcomings while reading the "SCS Standard Images" document in the official SCS docs at https://docs.scs.community/standards/scs-0104-v1-standard-images and trying to reach conformance to it.

### Current shortcomings

The standard spends a lot of time elaborating on the process of how images are standardized and how the standardization is implemented using YAML descriptions but little on how to figure out the currently standardized images.
My primary question as a CSP would be: "What images do I have to provide to be SCS compliant?". I don't feel this question is answered in a confident way. The standard currently only states this small sentence under the headlines "Lifecycle considerations"/"YAML lifecycle":

> The YAML file is generally located in this repository under `/Tests/iaas`.

Problems with that:

- This should be some kind of clickable permalink. The "in this repository" is a bad reference when reading the docs.scs.community page as a docs page.
    - Even if discovering and clicking the "GitHub" link on the top right of the page, it forwards to the docs repository, not the standards repository where the file resides.
- In my opinion, the wording of the sentence and its location in the standard does a poor job at communicating that this the central important YAML to achieve conformance with the standard. It sounds more like an example file similar to the code blocks illustrated in the preceeding sections.
    - At the bottom of the standard there is a link to OSISM's image manager which also ships YAML templates for images[^1] where as a CSP I could see myself asking instead: "are these the YAMLs I have to apply for the standard?"

### Suggestions for improvement

In general, I would like to improve the discoverability of the images YAML file[^2] and emphasize its role in relation to achieving standard conformance, just like in other standards (e.g. the flavor standard where mandatory and recommended flavors are listed directly in the standard):

- Provide a clickable reference link to the currently valid images YAML file[^2] (that also works on the rendered docs page) OR if possible, directly render the YAML into the docs page.
- Better communicate that the referenced YAML file is the binding standard regarding the list of mandatory/recommended images that need to be provisioned to achieve conformance to the standard.

I'd like to hear your opinion on this.

[^1]: https://github.com/osism/openstack-image-manager/tree/main/etc/images
[^2]: https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/scs-0104-v1-images.yaml

**Comment by mbuechse** [comment]
This is not controversial – I agree on all accounts. Thanks for spotting this.

**Comment by mbuechse** [comment]
For context: When we crafted this standard, the docs page wasn't as advanced nor as widely adopted as today. So it should be updated without question.

**Comment by mbuechse** [comment]
On second thought, the crux here is the following: from my point of view, this standard merely regulates the format of the YAML file; which YAML file is ultimately used is not part of the standard, but a parameter of the certificate subject. Well, apparently, this doesn't seem to be the most practical point of view... So this turns out to be something we should discuss in the SIG after all(!)

**Comment by mbuechse** [comment]
Let me expand on my previous statement. Currently, what YAML is relevant is solely determined in the [certificate scope](https://github.com/SovereignCloudStack/standards/blob/main/Tests/scs-compatible-iaas.yaml#L37):

```yaml
      - name: Standard images
        url: https://raw.githubusercontent.com/SovereignCloudStack/standards/main/Standards/scs-0104-v1-standard-images.md
        checks:
          - executable: ./iaas/standard-images/images-openstack.py
            args: -c {os_cloud} -d ./iaas/scs-0104-v1-images.yaml
            id: standard-images-check
```

Arguably, this is too arcane and not appropriate. We could introduce explicit parameters (that could then be listed in the docs, albeit in the docs for the certificate scope) like so:

```
      - name: Standard images
        url: https://raw.githubusercontent.com/SovereignCloudStack/standards/main/Standards/scs-0104-v1-standard-images.md
        parameters:
          images_yaml: https://raw.githubusercontent.com/SovereignCloudStack/standards/main/Tests/iaas/scs-0104-v1-images.yaml
        checks:
          - executable: ./iaas/standard-images/images-openstack.py
            args: -c {os_cloud} -d {images_yaml}
            id: standard-images-check
```

In this case, we would need to debate the type of the parameter -- if we want it clickable in the docs, a URL like in this example would be good, but I would also want to avoid the additional roundtrip for the download in the test script (so maybe include a special case for URLs that point to the same repo).

Another point of debate would be the presentation in the docs -- currently we have [this table](https://docs.scs.community/standards/scs-compatible-iaas): 

| Scope versions ->  | v2  | v3  | v4  |
| :-- | :-- | :-- | :-- |
| State              | Deprecated  | Effective  | Effective  |
| Stabilized at      | 2023-03-23  | 2023-06-15  | 2024-02-28  |
| Deprecated at      | 2023-11-30  | 2024-04-30  |   |
| **Standards**      |     |     |     |
| OpenStack Powered Compute  | [v2022.11](https://opendev.org/openinfra/interop/src/branch/master/guidelines/2022.11.json)  | [v2022.11](https://opendev.org/openinfra/interop/src/branch/master/guidelines/2022.11.json)  | [v2022.11](https://opendev.org/openinfra/interop/src/branch/master/guidelines/2022.11.json)  |
| scs-0100: Flavor naming  | [v2](/standards/scs-0100-v2-flavor-naming)  | [v3](/standards/scs-0100-v3-flavor-naming)  | [v3](/standards/scs-0100-v3-flavor-naming)  |
| scs-0101: Entropy  |   |   | [v1](/standards/scs-0101-v1-entropy)  |
| scs-0102: Image metadata  | [v1](/standards/scs-0102-v1-image-metadata)  | [v1](/standards/scs-0102-v1-image-metadata)  | [v1](/standards/scs-0102-v1-image-metadata)  |
| scs-0103: Standard flavors  |   |   | [v1](/standards/scs-0103-v1-standard-flavors)  |
| scs-0104: Standard images  |   |   | [v1](/standards/scs-0104-v1-standard-images)  |

The parameters would go in here somewhere, but obvoiusly we would need more space for them.
