### ISSUE TITLE
[BUG] namescheme for standard image "ubuntu-capi" wrong

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#537]
The mismatch has been noticed by @markus-hentsch in [this issue in the osism repo](https://github.com/osism/openstack-image-manager/issues/753)
The problem, however, is not with the image manager, but with the namescheme in the [standard images spec](https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/scs-0104-v1-images.yaml#L7):

```yaml
- name: "ubuntu-capi-image"
  name_scheme: "ubuntu-capi-image-v[0-9].[0-9]+(.[0-9]+)?"
  source: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube
  status: recommended
```

The namescheme should be `ubuntu-capi-image v[0-9].[0-9]+(.[0-9]+)?`
