### ISSUE TITLE
Drop github actions for compliance checking

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#931]
Several reasons:

- Let's not waste resources by running the tests redundantly with Zuul. Sometimes, these runs even interfere with each other.
- Remove redundant storage of secrets.
- Most problematic, however, the Github actions are generally out of sync with the now-standard Zuul jobs.

For instance:

```yaml
      - name: "Clean up any lingering resources from previous run"
        if: ${{ inputs.layer == 'iaas' && inputs.version == 'v4' }}
```

This is actually meant for v4 **and up**!

or

```yaml
  check-scs2:
    uses: ./.github/workflows/scs-compliance-check-with-application-credential.yml
    with:
      version: v5
      layer: iaas
      cloud: "scs2"
      secret_name: "OS_ACSECRET_SCS2"
    secrets: inherit
```

Correct would be `version: v5.1`.
